---
driver:
  name: vagrant
  provider: <%= ENV['KITCHEN_PROVIDER'] || 'virtualbox' %>

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ansible_cfg_path: test/vagrant/ansible.cfg
  enable_yum_epel: true
  ansible_host_key_checking: false
#  name: chef_solo
#  kerberos_conf_file:   <your krb5.conf file path> 

platforms:
  - name: ubuntu-20.04
  - name: ubuntu-18.04
  - name: centos-8
  - name: centos-7
#### http://kitchen.ci/blog/test-kitchen-windows-test-flight-with-vagrant/
#### FIXME! https://github.com/neillturner/kitchen-ansible/issues/131
#  - name: windows-2012r2
#    transport:
#      name: winrm
#    driver:
##      gui: false
#      gui: true


suites:
  - name: ansible
    run_list:
    attributes:
    driver_config:
      network:
#      - [ 'private_network', { type: 'dhcp' }]
      - [ 'private_network', { ip: '172.28.128.6' } ]
#      - [ 'public_network', { bridge: 'eth0' }]
    includes:
#      - centos-7.0
      - ubuntu-14.04
#    provisioner:
#      name: ansible_playbook
#      playbook: test/integration/ansible/ansiblespec/config.yml
#      ansible_connection: local
    provisioner:
      name: ansible_playbook
      playbook: test/integration/default/default.yml
      ansible_connection:  winrm
      require_windows_support: true  

  - name: windows
    driver_config:
      network:
#      - [ 'private_network', { type: 'dhcp' }]
      - [ 'private_network', { ip: '172.28.128.7' } ]
    includes:
      - windows-2012r2
