---

- name: Include version-specific variables for Ubuntu.
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
- name: Include version-specific variables for RedHat
  ansible.builtin.include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"
- name: Include version-specific variables for Alpine
  ansible.builtin.include_vars: "Alpine.yml"
  when: ansible_os_family == "Alpine"
- name: Include version-specific variables for Darwin
  ansible.builtin.include_vars: "Darwin.yml"
  when: ansible_os_family == "Darwin"

# FIXME! as redhat epel has still ansible 1.9. need to disable those 2 lines when testing this platform
- import_tasks: loki-windows.yml
  when: ansible_os_family == 'Windows'

- import_tasks: loki.yml
  when: ansible_os_family != 'Windows'

- name: Recover files on orchestrator
  ansible.builtin.fetch: "src={{ loki_output }} dest=tmp/"
  when: do_fetch is defined and do_fetch
