---

- name: Verify
  hosts: loki
  tasks:
    - name: Validate loki is present
      stat:
        path: /tmp/ir-bin/Loki/loki.py
      register: py
    - name: Validate loki
      assert:
        that: py.stat.exists and py.stat.executable
    - name: Validate scan output is present
      stat:
        path: /tmp/loki-out
      register: out
    - name: Validate scan output
      assert:
        that: out.stat.exists
